{% set name = "coastal-cascade" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/cascade/archive/v{{ version }}.tar.gz
  sha256: 71654933551980bf729663af1d2cce1ef57828cc8b961e10b0c427b565353d31

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - baked-brie
    - barrier3d
    - imageio
    - joblib
    - numpy
    - pyyaml

test:
  imports:
    - cascade
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/UNC-CECL/cascade
  summary: 'The CoAStal Community-lAnDscape Evolution model'
  description: |
    Cascade represents decisions about coastal land-use (e.g., housing markets) and
    community-level mitigation measures using an empirically-grounded agent-based
    real estate model – the Coastal Home Ownership Model (chom).
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://github.com/UNC-CECL/cascade
  dev_url: https://github.com/UNC-CECL/cascade

extra:
  recipe-maintainers:
    - mcflugen
